<%@ page import="java.util.*, java.text.DecimalFormat, model.Bill" %>
<%
    String isAdmin = (String) session.getAttribute("admin");
    if (isAdmin == null) {
%>
    <%@ include file="header.jsp" %>
<%
    }
%>

<%
    model.user u = (model.user) session.getAttribute("user");
    String role = null;
    if (u != null) {
        role = u.getRole();
    }
%>
<%@ page contentType="text/html;charset=UTF-8" %>

<!DOCTYPE html>
<html>
<head>
    <title>All Sales</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
<div class="container mt-5">
    <h3 class="bg-primary text-white text-center p-3 rounded">All Sales</h3>

    <table class="table table-bordered table-hover table-sm">
        <thead class="table-dark">
            <tr>
                <th class="text-center">#</th>
                <th class="text-center">Customer</th>
                <th class="text-center">Books Purchased</th>
                <th class="text-center">Total Amount (LKR)</th>
                <th class="text-center">Bill Date</th>
                <th class="text-center">Invoice Generated By</th>
                <th class="text-center">Action</th>
            </tr>
        </thead>
        <tbody>
        <%
            List<Bill> salesList = (List<Bill>) request.getAttribute("salesList");
            DecimalFormat df = new DecimalFormat("#,##0.00");
            int count = 1;
            if (salesList != null) {
                for (Bill sale : salesList) {
        %>
            <tr>
                <td class="text-center"><%= count++ %></td>
                <td><%= sale.getCustomerName() %> (<%= sale.getAccountNumber() %>)</td>
                <td><%= sale.getBooksPurchased() %></td>
                <td class="text-end"><%= df.format(sale.getTotalAmount()) %></td>
                <td class="text-center"><%= sale.getBillingTime() %></td>
                <td class="text-center"><%= sale.getStaffUsername()%></td>
                
                 <% if (!"Cashier".equalsIgnoreCase(role)) { %>
			      <td class="text-center">
			          <a href="deleteSale?id=<%= sale.getId() %>" class="btn btn-danger btn-sm"
			           onclick="return confirm('Are you sure you want to delete this customer?');">Delete</a>
			   	 </td>
			     <% } %>
                
            </tr>
        <%
                }
            }
        %>
        </tbody>
    </table>
    
    		<% if (salesList != null) { %>
			
			    <div class="mt-3 text-start">
			        <strong>Total Invoices: <%= salesList.size() %></strong>
			    </div>
			    
			<% } %>
			
			<% if (role == null) { %>
			
			<div class="mt-4 d-flex justify-content-center">
		    <a href="adminPanel.jsp">
		        <button class="btn btn-primary btn-lg">Back to Admin Panel</button>
		    </a>
		</div>
		<% } %>
</div>
</body>
</html>
