<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<%@ page import="java.util.*, java.text.DecimalFormat" %>
<%@ include file="header.jsp" %>

<%
    String acc = (String) request.getAttribute("accountNumber");
    String name = (String) request.getAttribute("customerName");
    double total = (Double) request.getAttribute("totalAmount");
    Date date = (Date) request.getAttribute("billDate");
    List<Map<String, Object>> items = (List<Map<String, Object>>) request.getAttribute("bookDetails");
    DecimalFormat df = new DecimalFormat("#,##0.00");
    
    %>
    
    

<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Invoice</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
<div class="container mt-4" style="max-width: 700px;">
    <h3 class="text-center bg-primary text-white p-3 rounded">Bill Preview</h3>

    <div class="mb-4">
        <p><strong>Customer Name:</strong> <%= name %></p>
        <p><strong>Account Number:</strong> <%= acc %></p>
        <p><strong>Date:</strong> <%= new java.text.SimpleDateFormat("yyyy-MM-dd HH:mm:ss").format(date) %></p>
    </div>
	
	<div class="mt-3"> <p><strong>Generated By:</strong> <%= username != null ? username : "Unknown User" %></p> </div>

    <table class="table table-bordered table-striped">
        <thead class="table-dark">
            <tr>
                <th>#</th>
                <th>Book Title</th>
                <th>Qty</th>
                <th>Unit Price (LKR)</th>
                <th>Total (LKR)</th>
            </tr>
        </thead>
        <tbody>
        <%
            int i = 1;
            for (Map<String, Object> item : items) {
        %>
            <tr>
                <td><%= i++ %></td>
                <td><%= item.get("title") %></td>
                <td><%= item.get("qty") %></td>
                <td><%= df.format(item.get("unitPrice")) %></td>
                <td><%= df.format(item.get("total")) %></td>
            </tr>
        <%
            }
        %>
        </tbody>
        <tfoot>
            <tr>
                <td colspan="4" class="text-end fw-bold">Grand Total</td>
                <td class="fw-bold"><%= df.format(total) %></td>
            </tr>
        </tfoot>
    </table>

    <div class="text-center mt-4">
        <button class="btn btn-primary" onclick="window.print()">Print Bill</button>
    </div>
</div>
</body>
</html>
